name: Build and Deploy
on:
  push:
    branches-ignore: ["*"]
    tags: ["*"]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') && github.repository == 'AWeber-Imbi/imbi-schema'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Build DDL
        run: make ddl
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: aweber/imbi-postgres
          tag_with_ref: true
